# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = serial.out
SRCS = main.cpp Data.cpp

include ../template.mk

Data.cpp: Data.hpp
main.cpp: Data.hpp
