# Any copyright is dedicated to the Public Domain.
# https://creativecommons.org/publicdomain/zero/1.0/

TARGET = identity.out
SRCS = main.cpp Base.cpp

include ../template.mk

Base.cpp: Base.hpp
main.cpp: Base.hpp A.hpp B.hpp C.hpp
